version: '3.1'

services:

  db:
    image: postgres
    ports:
      - "5433:5433"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
